### PR TITLE
added legal stuff

### PR DESCRIPTION
**Pull request by frunika**

### CODE REVIEW

**Comment by martinbaerwolff** [comment]
Legal stuff is not yet visible. Is this on purpose? Should I turn it visible (or review before)?

**Comment by frunika** [comment]
It is visible in the footer on every page but not in the menu. Should be enough

**Comment by martinbaerwolff** [comment]
Thats right, I did not see this due to cookie window...but "impressum" button is not working. I tried to fix it in 
documentation/themes/learn4/templates/partials/footer.html.twig, but could not find the problem.

**Comment by frunika** [comment]
Semms, that the dismiss button overlays the link. I'll try to fix that

**Pull request merged**
